---

- name: Compile python
  block:
    - name: Compile and install python
      block:
        - name: Setup fact with default artifact
          ansible.builtin.set_fact:
            python_default_artifact: "{{ python_default_artifact }}"

        - name: Setup fact with python latest versions
          ansible.builtin.set_fact:
            python_latest_versions: "{{ python_download_site_versions }}"
      when: python_artifact is undefined or python_version == "latest"

    - name: Gather package facts
      ansible.builtin.raw: >-
        /bin/bash -c
        "
        export LANGUAGE=en_US ;
        rpm -q {{ python_os_dependencies | join(' ') }}
        "
      register: python_gather_packages_result
      changed_when: no
      failed_when: no

    - name: Setup python dependencies
      ansible.builtin.raw: >-
        /bin/bash -c
        "
        export LANGUAGE=en_US ;
        if [ -f /usr/bin/dnf ]; then
        dnf install -y {{ python_os_dependencies | join(" ") }} ;
        else
        yum install -y  {{ python_os_dependencies | join(" ") }} ;
        fi
        "
      register: python_install_deps_result
      changed_when: >-
        python_install_deps_result.stdout is not search("Nothing to do")
      environment: "{{ proxy_client_environment | default({}) }}"

    - name: Setup source download directory
      ansible.builtin.raw: "mkdir -pv {{ python_source_download_dir }}"
      args:
        warn: no
      register: python_setup_download_dir_result
      changed_when: python_setup_download_dir_result.stdout_lines | length > 0

    - name: Download python source code
      ansible.builtin.raw: >-
        /bin/bash -c
        "
        if [ -f {{ python_artifact_path }} ]; then
        /bin/true ;
        else
        /usr/bin/curl
        {{ python_download_base_url }}/{{ python_download_file }}
        -o {{ python_artifact_path }} ;
        fi
        "
      register: python_download_result
      changed_when: python_download_result.stderr_lines | length > 0
      vars:
        python_artifact_path: >-
          {{ python_source_download_dir }}/{{ python_download_file }}

    - name: Configure python compilation
      ansible.builtin.raw: >-
        /bin/bash -c
        "
        {{ python_compilation_env }} ;
        cd {{ python_source_download_dir }} ;
        /bin/tar -zxvf {{ python_download_file }} ;
        cd {{ python_source_compile_dir }} ;
        ./configure {{ (python_compile_options
                        + ["--prefix="
                           + python_install_dir
                             | default(python_default_install_dir)]
                        + ["--with-openssl="
                           + openssl_install_dir
                             | default(openssl_default_install_dir)])
                       | list
                       | join(" ") }}
        "
      changed_when: yes

    - name: Compile and install python
      ansible.builtin.raw: >-
        /bin/bash -c
        "
        {{ python_compilation_env }} ;
        cd {{ python_source_compile_dir }} ;
        make install
        "
      changed_when: yes

    - name: Install python virtualenv package
      ansible.builtin.raw: >-
        /bin/bash -c
        "
        export LANGUAGE=en_US ;
        {{ python_pip_executable_file }} install virtualenv
        "
      register: python_install_virtualenv_result
      changed_when: >-
        python_install_virtualenv_result is search("Successfully installed")
  rescue:
    - name: Rescue cleanup
      ansible.builtin.include_tasks: rescue.yml
  environment: "{{ proxy_client_environment | default({}) }}"
