---

- name: Compile openssl
  block:
    - name: Download openssl source code
      ansible.builtin.raw: >-
        /bin/bash -c
        "
        if [ -f {{ openssl_artifact_path }} ]; then
        /bin/true ;
        else
        /usr/bin/curl {{ openssl_download_url }}
        -o {{ openssl_artifact_path }} ;
        fi
        "
      register: openssl_download_result
      changed_when: openssl_download_result.stderr_lines | length > 0
      vars:
        openssl_artifact_path: >-
          {{ python_tmp_dir }}/{{ openssl_download_file }}

    - name: Configure openssl compilation
      ansible.builtin.raw: >-
        /bin/bash -c
        "
        cd {{ python_tmp_dir }} ;
        /bin/tar -zxvf {{ openssl_download_file }} ;
        cd {{ openssl_source_compile_dir }} ;
        ./config {{ (python_openssl_compile_options
                      + ["--prefix="
                        + openssl_compiled_install_dir
                          | default(openssl_default_install_dir),
                        "--openssldir="
                        + openssl_compiled_install_dir
                          | default(openssl_default_install_dir)])
                    | list
                    | join(" ") }}
        "
      changed_when: yes

    - name: Compile and install openssl
      ansible.builtin.raw: >-
        /bin/bash -c
        "
        export LANGUAGE=en_US ;
        cd {{ openssl_source_compile_dir }} ;
        make ;
        make install ;
        echo "{{ openssl_default_install_dir }}/lib"
        > {{ python_ld_conf_path }} ;
        ldconfig
        "
      changed_when: yes
  rescue:
    - name: Rescue cleanup
      ansible.builtin.include_tasks: rescue.yml
