---

- name: Compile openssl
  block:
    - name: Download openssl source code
      ansible.builtin.raw: >-
        /bin/bash -c
        "
        if [ -f {{ openssl_artifact_path }} ]; then
        /bin/true ;
        else
        /usr/bin/curl {{ python_openssl_download_url }}
        -o {{ openssl_artifact_path }} ;
        fi
        "
      register: openssl_download_result
      changed_when: openssl_download_result.stderr_lines | length > 0
      vars:
        openssl_artifact_path: >-
          {{ python_tmp_dir }}/{{ python_openssl_download_file }}

    - name: Configure openssl build
      ansible.builtin.raw: >-
        /bin/bash -c
        "
        cd {{ python_tmp_dir }} ;
        /bin/tar -zxvf {{ python_openssl_download_file }} ;
        cd {{ python_openssl_source_build_dir }} ;
        ./config {{ (python_openssl_build_options
                      + ["--prefix="
                        + python_openssl_build_install_dir
                          | default(python_openssl_default_install_dir),
                        "--openssldir="
                        + python_openssl_build_install_dir
                          | default(python_openssl_default_install_dir)])
                    | list
                    | join(" ") }}
        "
      changed_when: yes

    - name: Compile and install openssl
      ansible.builtin.raw: >-
        /bin/bash -c
        "
        export LANGUAGE=en_US ;
        cd {{ python_openssl_source_build_dir }} ;
        make ;
        make install ;
        echo '{{ python_openssl_default_install_dir }}/lib'
        > {{ python_openssl_ld_conf_path }} ;
        ldconfig
        "
      changed_when: yes
  rescue:
    - name: Rescue cleanup
      ansible.builtin.include_tasks: rescue.yml
