---

- name: Compile python
  block:
    - name: Gather package facts
      ansible.builtin.raw: >-
        /bin/bash -c
        "
        export LANGUAGE=en_US ;
        rpm -q {{ python_build_os_dependencies | join(' ') }}
        "
      register: python_gather_packages_result
      changed_when: no
      failed_when: no

    - name: Setup python dependencies
      ansible.builtin.raw: >-
        /bin/bash -c
        "
        export LANGUAGE=en_US ;
        if [ -f /usr/bin/dnf ]; then
        dnf install -y {{ python_build_os_dependencies | join(" ") }} ;
        else
        yum install -y {{ python_build_os_dependencies | join(" ") }} ;
        fi
        "
      register: python_install_deps_result
      changed_when: >-
        python_install_deps_result.stdout is not search("Nothing to do")
      environment: "{{ proxy_client_environment | default({}) }}"

    - name: Setup source download directory
      ansible.builtin.raw: "mkdir -pv {{ python_tmp_dir }}"
      args:
        warn: no
      register: python_setup_download_dir_result
      changed_when: python_setup_download_dir_result.stdout_lines | length > 0

    - name: Download python source code
      ansible.builtin.raw: >-
        /bin/bash -c
        "
        if [ -f {{ python_artifact_path }} ]; then
        /bin/true ;
        else
        /usr/bin/curl
        {{ python_download_base_url }}/{{ python_download_file }}
        -o {{ python_artifact_path }} ;
        fi
        "
      register: python_download_result
      changed_when: python_download_result.stderr_lines | length > 0
      vars:
        python_artifact_path: >-
          {{ python_tmp_dir }}/{{ python_download_file }}

    - name: Configure python build
      ansible.builtin.raw: >-
        /bin/bash -c
        "
        {{ python_build_env }} ;
        cd {{ python_tmp_dir }} ;
        /bin/tar -zxvf {{ python_download_file }} ;
        cd {{ python_source_build_dir }} ;
        ./configure {{ (python_build_options
                        + ["--prefix="
                           + python_build_install_dir
                             | default(python_default_install_dir)]
                        + python_extra_build_options)
                       | list
                       | join(" ") }}
        "
      changed_when: yes

    - name: Compile and install python
      ansible.builtin.raw: >-
        /bin/bash -c
        "
        {{ python_build_env }} ;
        cd {{ python_source_build_dir }} ;
        make install
        "
      changed_when: yes

    - name: Install python virtualenv package
      ansible.builtin.raw: >-
        /bin/bash -c
        "
        export LANGUAGE=en_US ;
        {{ python_pip_path }} install virtualenv
        "
      register: python_install_virtualenv_result
      changed_when: >-
        python_install_virtualenv_result is search("Successfully installed")
  rescue:
    - name: Rescue cleanup
      ansible.builtin.include_tasks: rescue.yml
  environment: "{{ proxy_client_environment | default({}) }}"
