---

- name: Compile openssl
  block:
    - name: Setup source download directory
      ansible.builtin.raw: "mkdir -pv {{ python_source_download_dir }}"
      args:
        warn: no
      register: python_setup_download_dir_result
      changed_when: python_setup_download_dir_result.stdout_lines | length > 0

    - name: Download openssl source code
      ansible.builtin.raw: >-
        /bin/bash -c
        "
        if [ -f {{ openssl_artifact_path }} ]; then
        /bin/true ;
        else
        /usr/bin/curl {{ openssl_download_url }}
        -o {{ openssl_artifact_path }} ;
        fi
        "
      register: openssl_download_result
      changed_when: openssl_download_result.stderr_lines | length > 0
      vars:
        openssl_artifact_path: >-
          {{ python_source_download_dir }}/{{ openssl_download_file }}

    - name: Configure openssl compilation
      ansible.builtin.raw: >-
        /bin/bash -c
        "
        cd {{ python_source_download_dir }} ;
        /bin/tar -zxvf {{ openssl_download_file }} ;
        cd {{ openssl_source_compile_dir }} ;
        ./config {{ (openssl_compile_options
                      + ["--prefix="
                        + openssl_install_dir
                          | default(openssl_default_install_dir),
                        "--openssldir="
                        + openssl_install_dir
                          | default(openssl_default_install_dir)])
                    | list
                    | join(" ") }}
        "
      changed_when: yes

    # FIXME: Delete ld.config in clean
    - name: Compile and install openssl
      ansible.builtin.raw: >-
        /bin/bash -c
        "
        export LANGUAGE=en_US ;
        cd {{ openssl_source_compile_dir }} ;
        make ;
        make install ;
        echo "{{ openssl_default_install_dir }}/lib"
        > /etc/ld.so.conf.d/ansible_python_openssl.conf ;
        ldconfig
        "
      changed_when: yes
  rescue:
    - name: Rescue cleanup
      ansible.builtin.include_tasks: rescue.yml
