---

- name: Gather operating system release
  ansible.builtin.raw: >-
    cat /etc/centos-release 2> /dev/null \
    || cat /etc/redhat-release 2> /dev/null \
    || cat /etc/fedora-release 2> /dev/null
  args:
    warn: no
  changed_when: no
  failed_when: no
  register: python_os_result

- name: Setup fact with operating system info
  ansible.builtin.set_fact:
    python_distribution_name: >-
      {{ python_os_result.stdout
          | trim
          | regex_replace(python_os_release_regex, "\1") }}
    python_distribution_version: >-
      {{ python_os_result.stdout
          | trim
          | regex_replace(python_os_release_regex, "\2") }}
  vars:
    python_os_release_regex: "([a-zA-Z ]+) release ([0-9.]+).*"
