---

- name: Install development tools
  block:
    - name: Gather package facts
      ansible.builtin.raw: >-
        /bin/bash -c
        "
        export LANGUAGE=en_US ;
        rpm -q {{ python_os_dependencies | join(' ') }}
        "
      register: python_gather_packages_result
      changed_when: no
      failed_when: no

    - name: Setup python dependencies
      ansible.builtin.raw: >-
        /bin/bash -c
        "
        if [ -f /usr/bin/dnf ]; then
        dnf install -y {{ python_os_dependencies | join(" ") }} ;
        else
        yum install -y  {{ python_os_dependencies | join(" ") }} ;
        fi
        "
      register: python_install_deps_result
      changed_when: >-
        python_install_deps_result.stdout is not search("Nothing to do")
      environment: "{{ proxy_client_environment | default({}) }}"
  always:
    - name: Uninstall development tools
      ansible.builtin.include_tasks: uninstall_dev_tools.yml
  environment: "{{ proxy_client_environment | default({}) }}"
