---

- name: Gather info
  ansible.builtin.include_tasks: gather.yml

- name: Compile openssl and python
  ansible.builtin.include_tasks: compile.yml
  when: python_distribution_version is version("7", "<")

# FIXME: Complete for distros >= 7
