---
# Role install tasks
- name: Configure proxy if needed
  include_role:
    name: amtega.proxy_client
  vars:
    proxy_client_permanent: no
  when: python_use_proxy
- block:
    - name: Install python dependencies
      include_role:
        name: amtega.packages
      vars:
        packages_os: "{{ python_os_dependencies }}"

    - name: Create source download dir
      file:
        path: "{{ python_source_download_dir }}"
        state: directory
        mode: 0755

    - name: Download python source code
      include_role:
        name: amtega.artifact
      vars:
        overrides:
          state: present
        artifact: "{{ python_artifact | combine(overrides) }}"

    - name: Prepare makefile
      command: "./configure {{ python_compile_options | list | join(' ') }}"
      args:
        chdir: "{{ python_source_compile_dir }}"

    - name: Compile and install python
      command: make install
      args:
        chdir: "{{ python_source_compile_dir }}"

    - name: Install virtualenv
      pip:
        name: virtualenv
        state: present
        executable: "{{ python_pip_executable_file }}"

    - name: Clean artifact
      include_role:
        name: amtega.artifact
      vars:
        overrides:
          state: absent
        artifact: "{{ python_artifact | combine(overrides) }}"

    - name: Clean temporary source dirs
      file:
        path: "{{ source_dir }}"
        state: absent
      loop:
        - "{{ python_source_compile_dir }}"
        - "{{ python_source_download_dir }}"
      loop_control:
        loop_var: source_dir
