---
# Role install tasks

- name: Setup proxy
  include_role:
    name: amtega.proxy_client
  vars:
    proxy_client_permanent: no
  when: python_use_proxy | bool

- block:
    - name: Setup python dependencies
      include_role:
        name: amtega.packages
      vars:
        packages_os: "{{ python_os_dependencies }}"

    - name: Setup source download dir
      file:
        path: "{{ python_source_download_dir }}"
        state: directory
        mode: 0755

    - name: Download python source code
      include_role:
        name: amtega.artifact
      vars:
        overrides:
          state: present
        artifact: "{{ python_artifact | combine(overrides) }}"

    - name: Configure compilation
      command: >-
        ./configure {{ (python_compile_options
                        + ["--prefix=" + python_install_dir])
                       | list
                       | join(" ") }}
      args:
        chdir: "{{ python_source_compile_dir }}"

    - name: Compile and install python
      command: make install
      args:
        chdir: "{{ python_source_compile_dir }}"

    - name: Install virtualenv
      pip:
        name: virtualenv
        state: present
        executable: "{{ python_pip_executable_file }}"

    - name: Remove python source code
      include_role:
        name: amtega.artifact
      vars:
        overrides:
          state: absent
        artifact: "{{ python_artifact | combine(overrides) }}"

    - name: Remove temporary source directories
      file:
        path: "{{ python_source_dir }}"
        state: absent
      loop:
        - "{{ python_source_compile_dir }}"
        - "{{ python_source_download_dir }}"
      loop_control:
        loop_var: python_source_dir
