---

- name: Compile openssl and python
  ansible.builtin.include_tasks: compile.yml
  when: >-
    _python_distribution_version is version("7", "<")
    or not python_use_os_packages | bool

- name: Install python using operating system packages
  ansible.builtin.include_tasks: packages.yml
  when:
    - python_use_os_packages | bool
    - _python_distribution_version is version("7", ">=")

- name: Setup ansible python interpreter
  ansible.builtin.set_fact:
    ansible_python_interpreter: "{{ python_path }}"
  when: python_set_ansible_interpreter | bool
