---

- name: Gather operating system / python info
  ansible.builtin.include_tasks: gather.yml

- name: Install python
  ansible.builtin.include_tasks: install.yml
  when:
    - _python_install_required | bool
    - python_state == "present"
    - not python_gather_only | bool

- name: Uninstall python
  ansible.builtin.include_tasks: uninstall.yml
  when:
    - python_state == "absent"
    - not python_gather_only | bool
