---

- name: Install python operating system package
  ansible.builtin.raw: >-
    /bin/bash -c
    "
    export LANGUAGE=en_US ;
    if [ -f /usr/bin/dnf ]; then
    dnf install -y python3 ;
    else
    yum install -y python3 ;
    fi
    "
  register: python_install_package_result
  changed_when: >-
    python_install_package_result.stdout is not search("Nothing to do")
  environment: "{{ proxy_client_environment | default({}) }}"

- name: Install python PIP / virtualenv operating system package
  ansible.builtin.raw: >-
    /bin/bash -c
    "
    export LANGUAGE=en_US ;
    if /usr/bin/yum search virtualenv
    | grep -E "python3[0-9]*-virtualenv.noarch" ; then
    /usr/bin/yum install -y python3-virtualenv python3-pip;
    else
    /usr/bin/yum install -y epel-release ;
    /usr/bin/yum install -y python3-pip ;
    /usr/bin/yum install -y python3-virtualenv ;
    /usr/bin/yum remove -y epel-release ;
    fi
    "
  register: python_install_virtualenv_package_result
  changed_when: >-
    python_install_virtualenv_package_result.stdout
    is not search("Nothing to do")
