---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  roles:
    - role: amtega.python
      vars:
        python_gather_only: yes
  tasks:
    - name: Check python
      ansible.builtin.raw: "{{ python_path }} --version"
      changed_when: no

    - name: Check pip
      ansible.builtin.raw: "{{ python_pip_path }} --version"
      changed_when: no

    - name: Check virtualenv
      ansible.builtin.raw: "{{ python_virtualenv_path }} --version"
      changed_when: no
