---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Check python binary
      stat:
        path: /opt/python-3.9.7/bin/python3.9
      register: python_binary_check

    - name: Check pip binary
      stat:
        path: /opt/python-3.9.7/bin/pip3.9
      register: python_pip_binary_check

    - name: Verify binary install
      assert:
        that:
          - python_binary_check.stat.exists
          - python_pip_binary_check.stat.exists
