---

- name: Verify virtualenv in EL hosts
  hosts: molecule_hosts:!molecule_hosts_centos_6:!molecule_hosts_fedora
  gather_facts: no
  tasks:
    - name: Check virtualenv
      ansible.builtin.command: /usr/bin/virtualenv-3 --version
      changed_when: no

- name: Verify virtualenv in fedora hosts
  hosts: molecule_hosts_fedora
  gather_facts: no
  tasks:
    - name: Check virtualenv
      ansible.builtin.command: /usr/bin/virtualenv --version
      changed_when: no

- name: CentOS 6 verify
  hosts: molecule_hosts_centos_6
  gather_facts: no
  tasks:
    - name: Check python
      ansible.builtin.command: "{{ python_executable_file_path }} --version"
      changed_when: no

    - name: Check pip
      ansible.builtin.command: "{{ python_pip_executable_file_path }} --version"
      changed_when: no

    - name: Check virtualenv
      ansible.builtin.command: >-
        {{ python_virtualenv_executable_file_path }} --version
      changed_when: no
  vars:
    ansible_python_interpreter: "{{ python_executable_file_path }}"
